# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.runs/synth_1/basys3_ai_demo.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.cache/wt [current_project]
set_property parent.project_path C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/ai_accelerator_bus.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/ai_accelerator_top.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/ai_compute_engine.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/ai_dot4.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/ai_pe.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/ai_stream_controller.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/ai_systolic_4x4.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_ai_soc_basys3.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_alu.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_branch_unit.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_decoder.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_forwarding.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_hazard.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_pipeline.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/riscv_regfile.v
  C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/sources_1/new/basys3_ai_demo.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/constrs_1/new/basys3_ai_demo.xdc
set_property used_in_implementation false [get_files C:/Users/Unnathi/riscv_ai_accelerator/riscv_ai_accelerator.srcs/constrs_1/new/basys3_ai_demo.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top basys3_ai_demo -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef basys3_ai_demo.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file basys3_ai_demo_utilization_synth.rpt -pb basys3_ai_demo_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
